'use client';

import { AlertTriangle, ArrowRight, CheckCircle2, CircleAlert, PackageCheck, ShieldCheck } from 'lucide-react';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { StatusBadge } from '@/components/StatusBadge';
import { useAssurance, useEvents, useFulfilment } from '@/hooks/useAssurance';

const requirementId = process.env.NEXT_PUBLIC_REQUIREMENT_ID ?? (process.env.NEXT_PUBLIC_APP_MODE === 'demo' ? '00000000-0000-0000-0000-000000000500' : '');

export function CommandCenter() {
  const assurance = useAssurance(requirementId);
  const fulfilment = useFulfilment(requirementId);
  const events = useEvents(requirementId);
  if (assurance.isLoading) return <CommandLoading />;
  if (!assurance.data) return <CommandError message={assurance.error?.message} />;
  const data = assurance.data;
  const required = Number(data.requirement.required_quantity_kg);
  const committed = Number(data.committed_quantity_kg);
  const standby = Number(data.standby_quantity_kg);
  const shortfall = Number(data.unfilled_quantity_kg);
  const coverage = required ? Math.round(committed / required * 100) : 0;
  const attention = data.supply_health !== 'COVERED';
  const parishTotals = data.allocations.filter(item => item.role === 'COMMITTED' && item.status !== 'LOST').reduce<Record<string, number>>((result, item) => { result[item.parish] = (result[item.parish] ?? 0) + Number(item.quantity_kg); return result; }, {});
  const maxParish = Object.entries(parishTotals).sort((a, b) => b[1] - a[1])[0];
  return <AppShell programme={`${data.requirement.buyer_name} · ${data.requirement.crop}`}><main className="mx-auto max-w-[1540px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8">
    <header className="mb-7"><p className="section-eyebrow">KoroFarm</p><h1 className="mt-2 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">Supply Assurance Control Room</h1><p className="mt-2 text-sm text-muted-foreground">Observe commitments, prioritize exceptions, and protect institutional demand.</p></header>
    <section className="grid border-y border-white/[0.08] sm:grid-cols-4"><Metric label="Active requirements" value="1" detail="Configured workspace" /><Metric label="Covered" value={data.supply_health === 'COVERED' ? '1' : '0'} tone="success" detail={`${coverage}% coverage`} /><Metric label="At risk" value={data.supply_health === 'AT_RISK' ? '1' : '0'} tone="warning" detail={`${shortfall} kg shortfall`} /><Metric label="Escalation required" value={data.supply_health === 'ESCALATION_REQUIRED' ? '1' : '0'} tone="critical" detail="Unresolved exceptions" /></section>
    <section className="mt-7 operational-panel overflow-hidden"><SectionTitle eyebrow="Exception queue" title="Needs attention" action={attention ? '1 open exception' : 'All clear'} />{attention ? <Link href={`/requirements/${data.requirement.id}`} className="grid gap-4 border-t border-warning/20 bg-warning/[0.035] px-5 py-5 hover:bg-warning/[0.055] md:grid-cols-[120px_minmax(0,1fr)_150px_130px_24px] md:items-center"><StatusBadge status={data.supply_health} /><div><p className="font-medium">Grade {data.requirement.grade} {data.requirement.crop.toLowerCase()}</p><p className="mt-1 text-xs text-muted-foreground">{data.requirement.buyer_name} · committed supply disruption</p></div><div><p className="tabular text-lg font-semibold text-destructive">{shortfall} kg</p><p className="text-[10px] uppercase tracking-wider text-muted-foreground">Quantity impact</p></div><div><p className="text-xs font-medium">Review recovery plan</p><p className="mt-1 text-[10px] text-muted-foreground">Open now</p></div><ArrowRight className="h-4 w-4 text-muted-foreground" /></Link> : <div className="border-t border-white/[0.07] px-5 py-8 text-center"><CheckCircle2 className="mx-auto h-5 w-5 text-success" /><p className="mt-3 text-sm font-medium">No supply disruptions require attention.</p><p className="mt-1 text-xs text-muted-foreground">The configured requirement is currently covered.</p></div>}</section>
    <section className="mt-7 operational-panel overflow-hidden"><SectionTitle eyebrow="Operating portfolio" title="Active programmes" action="1 authoritative requirement" /><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-y border-white/[0.07] text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{['Programme','Buyer','Commodity','Required','Committed','Coverage','Standby','Status','Risk','Next delivery'].map(label => <th key={label} className="px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody><tr className="hover:bg-white/[0.02]"><td className="px-4 py-4"><Link href={`/requirements/${data.requirement.id}`} className="font-medium text-primary hover:underline">Ginger supply programme</Link></td><td className="px-4 py-4 text-xs">{data.requirement.buyer_name}</td><td className="px-4 py-4">Grade {data.requirement.grade} {data.requirement.crop}</td><td className="tabular px-4 py-4">{required} kg</td><td className="tabular px-4 py-4">{committed} kg</td><td className="tabular px-4 py-4">{coverage}%</td><td className="tabular px-4 py-4 text-accent">{standby} kg</td><td className="px-4 py-4"><StatusBadge status={data.supply_health} /></td><td className="px-4 py-4">{data.risk?.label ?? 'UNKNOWN'}</td><td className="px-4 py-4 text-xs text-muted-foreground">{data.requirement.delivery_window_start}</td></tr></tbody></table></div></section>
    <section className="mt-7 grid gap-6 lg:grid-cols-3"><div className="operational-panel p-5"><p className="section-eyebrow">Today's physical flow</p><h2 className="mt-2 text-lg font-semibold">Receiving position</h2><div className="mt-5 grid grid-cols-2 gap-4"><SmallMetric label="Expected" value={`${fulfilment.data?.required_kg ?? '—'} kg`} /><SmallMetric label="Received" value={`${fulfilment.data?.received_kg ?? '—'} kg`} tone="info" /><SmallMetric label="Accepted" value={`${fulfilment.data?.accepted_kg ?? '—'} kg`} tone="success" /><SmallMetric label="Rejected" value={`${fulfilment.data?.rejected_kg ?? '—'} kg`} tone="critical" /></div><p className="mt-4 flex gap-2 border-t border-white/[0.07] pt-4 text-xs text-muted-foreground"><PackageCheck className="h-3.5 w-3.5 text-accent" />Receipt is not acceptance.</p></div><div className="operational-panel p-5"><p className="section-eyebrow">Network health</p><h2 className="mt-2 text-lg font-semibold">Supply resilience</h2><div className="mt-5 divide-y divide-white/[0.07]"><HealthRow label="Largest parish exposure" value={maxParish ? `${maxParish[0]} · ${Math.round(maxParish[1] / committed * 100)}%` : 'Unknown'} /><HealthRow label="Standby depth" value={`${Math.round(standby / required * 100)}%`} /><HealthRow label="Open disruptions" value={attention ? '1' : '0'} /></div></div><div className="operational-panel overflow-hidden"><div className="p-5"><p className="section-eyebrow">Recent agent activity</p><h2 className="mt-2 text-lg font-semibold">Decision ledger</h2></div><ol className="divide-y divide-white/[0.06]">{events.data?.slice(-3).reverse().map(event => <li key={event.id} className="flex gap-3 px-5 py-3"><span className="mt-0.5 grid h-6 w-6 shrink-0 place-items-center rounded-full bg-accent/10 text-accent"><ShieldCheck className="h-3 w-3" /></span><div><p className="text-xs font-medium">{event.event_type.replace(/\./g, ' ')}</p><p className="mt-1 text-[10px] text-muted-foreground">{new Date(event.occurred_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })} · {event.actor_type}</p></div></li>) ?? <li className="px-5 py-8 text-center text-xs text-muted-foreground">Activity unavailable</li>}</ol></div></section>
    <p className="mt-7 flex items-start gap-2 text-xs text-muted-foreground"><CircleAlert className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent" />Portfolio aggregation is limited to the configured requirement because the backend does not expose a requirement-list API. No additional programmes are fabricated.</p>
  </main></AppShell>;
}

function Metric({ label, value, detail, tone }: { label: string; value: string; detail: string; tone?: 'success' | 'warning' | 'critical' }) { const color = tone === 'success' ? 'text-success' : tone === 'warning' ? 'text-warning' : tone === 'critical' ? 'text-destructive' : 'text-foreground'; return <div className="border-b border-white/[0.07] px-5 py-5 last:border-b-0 sm:border-b-0 sm:border-r sm:last:border-r-0"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-muted-foreground">{label}</p><p className={`tabular mt-2 text-3xl font-semibold ${color}`}>{value}</p><p className="mt-1 text-[10px] text-muted-foreground">{detail}</p></div>; }
function SmallMetric({ label, value, tone }: { label: string; value: string; tone?: 'success' | 'critical' | 'info' }) { return <div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={`tabular mt-1 text-lg font-semibold ${tone === 'success' ? 'text-success' : tone === 'critical' ? 'text-destructive' : tone === 'info' ? 'text-accent' : ''}`}>{value}</p></div>; }
function HealthRow({ label, value }: { label: string; value: string }) { return <div className="flex items-center justify-between py-3 text-xs"><span className="text-muted-foreground">{label}</span><strong>{value}</strong></div>; }
function SectionTitle({ eyebrow, title, action }: { eyebrow: string; title: string; action: string }) { return <div className="flex items-end justify-between gap-4 px-5 py-5"><div><p className="section-eyebrow">{eyebrow}</p><h2 className="mt-2 text-xl font-semibold">{title}</h2></div><span className="text-xs text-muted-foreground">{action}</span></div>; }
function CommandLoading() { return <div className="grid min-h-screen place-items-center"><div className="h-64 w-[min(90vw,900px)] animate-pulse rounded-xl border border-white/[0.07] bg-card"><span className="sr-only">Loading command center</span></div></div>; }
function CommandError({ message }: { message?: string }) { return <div className="grid min-h-screen place-items-center px-6"><div role="alert" className="operational-panel max-w-md p-7"><AlertTriangle className="h-5 w-5 text-warning" /><h1 className="mt-3 text-xl font-semibold">Command Center unavailable</h1><p className="mt-2 text-sm text-muted-foreground">{message ?? 'Authoritative state could not be loaded.'} No portfolio data was substituted.</p></div></div>; }
