import { AlertTriangle, PackageCheck } from 'lucide-react';
interface Summary { required_kg: string; committed_kg?: string; received_kg: string; accepted_kg: string; rejected_kg: string; accepted_shortfall_kg?: string }

export function FulfilmentPanel({ summary }: { summary?: Summary | null }) {
  if (!summary) return <section id="fulfilment" className="operational-panel p-5"><p className="section-eyebrow">Physical fulfilment</p><h2 className="mt-2 text-lg font-semibold">Receiving & quality</h2><p className="mt-5 text-sm text-muted-foreground">Physical state is unavailable. No quantity is assumed.</p></section>;
  const quantities = [
    ['Expected', summary.required_kg, 'text-foreground'], ['Received', summary.received_kg, 'text-accent'],
    ['Accepted', summary.accepted_kg, 'text-success'], ['Rejected', summary.rejected_kg, Number(summary.rejected_kg) ? 'text-destructive' : 'text-muted-foreground'],
  ];
  return <section id="fulfilment" className="operational-panel p-5" aria-labelledby="fulfilment-title"><div className="flex items-start justify-between gap-4"><div><p className="section-eyebrow">Physical fulfilment</p><h2 id="fulfilment-title" className="mt-2 text-lg font-semibold">Receiving & quality</h2></div><span className="rounded-md border border-white/[0.08] px-2 py-1 text-[10px] uppercase tracking-wider text-muted-foreground">{Number(summary.received_kg) ? 'In progress' : 'Awaiting receipt'}</span></div><div className="mt-5 grid grid-cols-2 divide-x divide-y divide-white/[0.07] border-y border-white/[0.07] sm:grid-cols-4 sm:divide-y-0">{quantities.map(([label, value, tone]) => <div className="px-3 py-4 first:pl-0" key={label}><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={`tabular mt-1 text-xl font-semibold ${tone}`}>{Number(value).toLocaleString('en-JM')}<span className="ml-1 text-xs font-normal text-muted-foreground">kg</span></p></div>)}</div><p className="mt-4 flex items-start gap-2 text-xs leading-5 text-muted-foreground">{Number(summary.rejected_kg) ? <AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-destructive" /> : <PackageCheck className="mt-0.5 h-3.5 w-3.5 shrink-0 text-accent" />}Receipt is not acceptance. Accepted supply requires inspection evidence before shipment or reconciliation.</p></section>;
}
