import { CheckCircle2, MapPin, PackageCheck } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
interface FulfilmentSummary { received_kg: string; accepted_kg: string; rejected_kg: string }

export function FulfilmentPanel({ summary }: { summary?: FulfilmentSummary | null }) {
  return <Card><CardHeader className="pb-4"><p className="font-mono text-xs uppercase tracking-[0.18em] text-primary">Physical fulfilment</p><CardTitle className="mt-2 text-lg">Collection node</CardTitle></CardHeader><CardContent><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><MapPin className="mt-0.5 h-5 w-5 text-primary" /><div><p className="font-medium">Collection node</p><p className="mt-1 text-xs text-muted-foreground">One consolidation point · farmer identity retained</p></div></div><Badge variant="outline" className="whitespace-nowrap">{summary?.received_kg === '0.000' ? 'Awaiting receipt' : 'In progress'}</Badge></div><div className="mt-6 grid grid-cols-3 gap-2 text-center"><Metric label="Received" value={`${summary?.received_kg ?? '0'} kg`} /><Metric label="Accepted" value={`${summary?.accepted_kg ?? '0'} kg`} /><Metric label="Rejected" value={`${summary?.rejected_kg ?? '0'} kg`} /></div><div className="mt-5 flex items-center gap-2 border-t border-border/60 pt-4 text-xs text-muted-foreground"><PackageCheck className="h-4 w-4 text-muted-foreground" />Evidence required before reconciliation</div></CardContent></Card>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-muted/50 p-2"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 font-mono text-sm font-semibold">{value}</p></div>; }