'use client';

import { AlertTriangle, ArrowDown, Check, CircleAlert, FileCheck2, Package, PlugZap, Search, ShieldCheck, UserRound } from 'lucide-react';
import Link from 'next/link';
import { AppShell } from '@/components/AppShell';
import { AllocationTable } from '@/components/AllocationTable';
import { DataTrustIndicator } from '@/components/DataTrustIndicator';
import { FulfilmentPanel } from '@/components/FulfilmentPanel';
import { HonestEmpty, WorkspaceHeader, Breadcrumbs } from '@/components/WorkspacePrimitives';
import { StatusBadge } from '@/components/StatusBadge';
import { useAssurance, useEvents, useFulfilment } from '@/hooks/useAssurance';
import type { Allocation } from '@/lib/mockdata';

export type WorkspaceKind = 'programmes' | 'demand' | 'supply' | 'assurance' | 'fulfilment' | 'network' | 'compliance' | 'traceability' | 'trade-evidence' | 'analytics' | 'agent-operations' | 'activity' | 'integrations' | 'settings' | 'programme' | 'farmer';
const requirementId = process.env.NEXT_PUBLIC_REQUIREMENT_ID ?? (process.env.NEXT_PUBLIC_APP_MODE === 'demo' ? '00000000-0000-0000-0000-000000000500' : '');

const copy: Record<WorkspaceKind, [string, string, string]> = {
  programmes: ['Operations', 'Programmes', 'Institutional supply relationships and their active demand.'], demand: ['Operations', 'Demand', 'Buyer requirements, quantities, delivery windows, and assurance state.'], supply: ['Operations', 'Supply Network', 'Farmer allocations and production lots contributing to current commitments.'], assurance: ['Exception management', 'Assurance Center', 'Find shortfalls, available recovery capacity, and unresolved escalation.'], fulfilment: ['Physical operations', 'Fulfilment Center', 'Track expected, received, accepted, and rejected quantities without collapsing physical states.'], network: ['Intelligence', 'Network Intelligence', 'Understand parish distribution, concentration, and authorized standby depth.'], compliance: ['Trust', 'Compliance Registry', 'Only authoritative, verified trade-route rules belong here.'], traceability: ['Trust', 'Traceability Explorer', 'Follow available provenance links without inventing missing physical evidence.'], 'trade-evidence': ['Trust', 'Trade Evidence', 'Auditable fulfilment records issued only after verified reconciliation.'], analytics: ['Intelligence', 'Analytics', 'Current-state metrics derived from authoritative quantities.'], 'agent-operations': ['System', 'Agent Operations', 'Structured triggers, actions, outcomes, and audit links—never hidden chain-of-thought.'], activity: ['System ledger', 'Activity & Audit', 'Chronological state-changing events for the configured requirement.'], integrations: ['System', 'Integrations', 'Configuration posture for actual platform dependencies.'], settings: ['Administration', 'Settings', 'Environment, access, and data-authority posture.'], programme: ['Programme workspace', 'Ginger Supply Programme', 'A concise operating view of the configured institutional supply programme.'], farmer: ['Supply partner', 'Farmer workspace', 'Allocation-derived operating context. Trade history and financing remain explicitly separate.'],
};

export function ModuleWorkspace({ kind, entityId }: { kind: WorkspaceKind; entityId?: string }) {
  const assurance = useAssurance(requirementId); const fulfilment = useFulfilment(requirementId); const events = useEvents(requirementId);
  const [eyebrow, title, description] = copy[kind];
  if (assurance.isLoading) return <div className="grid min-h-screen place-items-center"><div className="h-56 w-[min(90vw,900px)] animate-pulse rounded-xl bg-card"><span className="sr-only">Loading workspace</span></div></div>;
  if (!assurance.data) return <div className="grid min-h-screen place-items-center px-6"><div role="alert" className="operational-panel max-w-md p-7"><AlertTriangle className="h-5 w-5 text-warning" /><h1 className="mt-3 text-xl font-semibold">Workspace unavailable</h1><p className="mt-2 text-sm text-muted-foreground">{assurance.error?.message ?? 'No authoritative requirement is configured.'}</p></div></div>;
  const data = assurance.data;
  const allocations: Allocation[] = data.allocations.map(item => ({ id: item.id, farmer: item.farmer_name, farmerId: item.farmer_id, parish: item.parish, lotId: item.production_lot_id, quantityKg: Number(item.quantity_kg), role: item.role, status: item.status as Allocation['status'] }));
  const programme = `${data.requirement.buyer_name} · ${data.requirement.crop}`;
  return <AppShell programme={programme}><main className="mx-auto max-w-[1540px] px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><Breadcrumbs items={[{ label: 'Command Center', href: '/' }, { label: title }]} /><WorkspaceHeader eyebrow={eyebrow} title={kind === 'farmer' ? allocations.find(item => item.farmerId === entityId)?.farmer ?? title : title} description={description} trust={<DataTrustIndicator state="SYSTEM DERIVED" detail="Rendered from the configured requirement API" />} />{renderKind(kind, { data, allocations, fulfilment: fulfilment.data, events: events.data ?? [], entityId })}</main></AppShell>;
}

type Context = { data: NonNullable<ReturnType<typeof useAssurance>['data']>; allocations: Allocation[]; fulfilment?: ReturnType<typeof useFulfilment>['data']; events: NonNullable<ReturnType<typeof useEvents>['data']>; entityId?: string };
function renderKind(kind: WorkspaceKind, context: Context) {
  const { data, allocations, fulfilment, events, entityId } = context; const required = Number(data.requirement.required_quantity_kg); const committed = Number(data.committed_quantity_kg); const standby = Number(data.standby_quantity_kg); const shortfall = Number(data.unfilled_quantity_kg); const coverage = required ? Math.round(committed / required * 100) : 0;
  if (kind === 'programmes' || kind === 'demand') return <RequirementTable data={data} required={required} committed={committed} standby={standby} coverage={coverage} mode={kind} />;
  if (kind === 'programme') return <ProgrammeSummary data={data} required={required} committed={committed} standby={standby} fulfilment={fulfilment} events={events} />;
  if (kind === 'supply') return <><div className="mb-6 grid gap-4 sm:grid-cols-3"><Summary label="Committed farmers" value={String(data.committed_farmer_count)} /><Summary label="Standby farmers" value={String(data.standby_farmer_count)} tone="info" /><Summary label="Authorized standby" value={`${standby} kg`} tone="info" /></div><AllocationTable allocations={allocations} /></>;
  if (kind === 'farmer') return <FarmerView farmer={allocations.find(item => item.farmerId === entityId) ?? allocations[0]} allocations={allocations} />;
  if (kind === 'assurance') return <><div className="grid gap-4 sm:grid-cols-4"><Summary label="Required" value={`${required} kg`} /><Summary label="Committed" value={`${committed} kg`} tone={shortfall ? 'warning' : 'success'} /><Summary label="Shortfall" value={`${shortfall} kg`} tone={shortfall ? 'critical' : 'success'} /><Summary label="Standby" value={`${standby} kg`} tone="info" /></div><div className="mt-6 operational-panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><div><p className="section-eyebrow">All requirements</p><h2 className="mt-2 text-lg font-semibold">Assurance queue</h2></div><StatusBadge status={data.supply_health} /></div><RequirementRow data={data} required={required} committed={committed} standby={standby} coverage={coverage} /></div></>;
  if (kind === 'fulfilment') return <><FulfilmentPanel summary={fulfilment} /><div className="mt-6 operational-panel"><HonestEmpty title="No receiving action is available in this workspace" detail="The backend supports receipt and grading commands, but the current frontend does not yet expose operator entry forms. Existing quantities remain visible and authoritative." action="Receiving UI is deferred—not simulated." /></div></>;
  if (kind === 'network') return <NetworkView allocations={allocations} committed={committed} standby={standby} required={required} />;
  if (kind === 'compliance') return <RegistryEmpty icon={FileCheck2} title="NO VERIFIED RULE ON FILE" detail="No verified compliance object is available in the configured requirement view. KoroFarm will not convert an explanation into a regulatory fact." />;
  if (kind === 'traceability') return <TraceabilityView />;
  if (kind === 'trade-evidence') return <RegistryEmpty icon={ShieldCheck} title="BUILDING HISTORY" detail="Verified trade evidence requires delivery, buyer confirmation, and reconciliation. Financing remains NOT ASSESSED." />;
  if (kind === 'analytics') return <AnalyticsView required={required} committed={committed} standby={standby} shortfall={shortfall} fulfilment={fulfilment} data={data} />;
  if (kind === 'agent-operations') return <AgentView data={data} events={events} />;
  if (kind === 'activity') return <ActivityView events={events} />;
  if (kind === 'integrations') return <IntegrationView />;
  return <SettingsView />;
}

function RequirementTable({ data, required, committed, standby, coverage, mode }: { data: Context['data']; required: number; committed: number; standby: number; coverage: number; mode: 'programmes' | 'demand' }) { return <section className="operational-panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/[0.07] px-5 py-4"><p className="text-xs text-muted-foreground">1 configured {mode === 'programmes' ? 'programme' : 'requirement'}</p><span className="flex items-center gap-2 text-xs text-muted-foreground"><Search className="h-3.5 w-3.5" />Search unavailable across unlisted records</span></div><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-sm"><thead className="text-[10px] uppercase tracking-wider text-muted-foreground"><tr>{['Reference','Buyer','Commodity','Required','Committed','Standby','Coverage','Status','Delivery'].map(label => <th key={label} className="border-b border-white/[0.07] px-4 py-3 font-medium">{label}</th>)}</tr></thead><tbody><tr><td className="px-4 py-4"><Link className="font-mono text-xs text-primary hover:underline" href={`/requirements/${data.requirement.id}`}>{mode === 'programmes' ? 'GINGER-PROGRAMME' : data.requirement.id.slice(0, 13)}</Link></td><td className="px-4 py-4">{data.requirement.buyer_name}</td><td className="px-4 py-4">Grade {data.requirement.grade} {data.requirement.crop}</td><td className="tabular px-4 py-4">{required} kg</td><td className="tabular px-4 py-4">{committed} kg</td><td className="tabular px-4 py-4 text-accent">{standby} kg</td><td className="tabular px-4 py-4">{coverage}%</td><td className="px-4 py-4"><StatusBadge status={data.supply_health} /></td><td className="px-4 py-4 text-xs text-muted-foreground">{data.requirement.delivery_window_start}</td></tr></tbody></table></div><p className="border-t border-white/[0.07] px-5 py-4 text-xs text-muted-foreground">A complete registry requires a backend list endpoint. This view does not invent additional records.</p></section>; }
function RequirementRow({ data, required, committed, standby, coverage }: { data: Context['data']; required: number; committed: number; standby: number; coverage: number }) { return <Link href={`/requirements/${data.requirement.id}`} className="grid gap-4 px-5 py-5 hover:bg-white/[0.02] md:grid-cols-[minmax(0,1.5fr)_repeat(4,110px)_24px] md:items-center"><div><p className="font-medium">Grade {data.requirement.grade} {data.requirement.crop.toLowerCase()}</p><p className="mt-1 text-xs text-muted-foreground">{data.requirement.buyer_name}</p></div><Mini label="Required" value={`${required} kg`} /><Mini label="Committed" value={`${committed} kg`} /><Mini label="Standby" value={`${standby} kg`} /><Mini label="Coverage" value={`${coverage}%`} /><ArrowDown className="h-4 w-4 -rotate-90 text-muted-foreground" /></Link>; }
function ProgrammeSummary({ data, required, committed, standby, fulfilment, events }: { data: Context['data']; required: number; committed: number; standby: number; fulfilment?: Context['fulfilment']; events: Context['events'] }) { return <><div className="grid gap-4 sm:grid-cols-4"><Summary label="Required" value={`${required} kg`} /><Summary label="Committed" value={`${committed} kg`} tone="success" /><Summary label="Standby" value={`${standby} kg`} tone="info" /><Summary label="Accepted" value={`${fulfilment?.accepted_kg ?? '—'} kg`} /></div><section className="mt-6 grid gap-6 lg:grid-cols-2"><div className="operational-panel p-5"><p className="section-eyebrow">Programme identity</p><dl className="mt-4 divide-y divide-white/[0.07] text-sm"><Pair label="Buyer" value={data.requirement.buyer_name} /><Pair label="Destination" value={data.requirement.destination} /><Pair label="Delivery period" value={`${data.requirement.delivery_window_start} – ${data.requirement.delivery_window_end}`} /><Pair label="Assurance" value={data.supply_health} /></dl></div><div className="operational-panel p-5"><p className="section-eyebrow">Latest activity</p>{events.slice(-3).reverse().map(event => <p key={event.id} className="border-b border-white/[0.07] py-3 text-xs">{event.event_type.replace(/\./g, ' ')} <span className="float-right text-muted-foreground">{event.actor_type}</span></p>)}</div></section></>; }
function FarmerView({ farmer, allocations }: { farmer: Allocation; allocations: Allocation[] }) { const own = allocations.filter(item => item.farmerId === farmer.farmerId); return <><div className="grid gap-4 sm:grid-cols-4"><Summary label="Region" value={farmer.parish} /><Summary label="Active lots" value={String(new Set(own.map(item => item.lotId)).size)} /><Summary label="Committed" value={`${own.filter(item => item.role === 'COMMITTED').reduce((s, item) => s + item.quantityKg, 0)} kg`} tone="success" /><Summary label="Standby" value={`${own.filter(item => item.role === 'STANDBY').reduce((s, item) => s + item.quantityKg, 0)} kg`} tone="info" /></div><section className="mt-6 operational-panel p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-primary/10 text-primary"><UserRound className="h-5 w-5" /></span><div><p className="font-medium">Synthetic demo supply partner</p><p className="text-xs text-muted-foreground">No reliability or credit score is calculated.</p></div></div><div className="mt-5 grid gap-4 border-t border-white/[0.07] pt-5 sm:grid-cols-2"><Mini label="Trade history" value="BUILDING HISTORY" /><Mini label="Financing" value="NOT ASSESSED" /></div></section></>; }
function NetworkView({ allocations, committed, standby, required }: { allocations: Allocation[]; committed: number; standby: number; required: number }) { const totals = allocations.filter(a => a.role === 'COMMITTED' && a.status !== 'LOST').reduce<Record<string, number>>((r, a) => { r[a.parish] = (r[a.parish] ?? 0) + a.quantityKg; return r; }, {}); return <div className="grid gap-6 lg:grid-cols-[1fr_0.55fr]"><section className="operational-panel p-5"><p className="section-eyebrow">Supply by parish</p><div className="mt-6 space-y-5">{Object.entries(totals).sort((a,b)=>b[1]-a[1]).map(([parish,value]) => <div key={parish}><div className="flex justify-between text-xs"><span>{parish}</span><span className="tabular text-muted-foreground">{value} kg · {Math.round(value / committed * 100)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded bg-white/[0.06]"><div className="h-full bg-accent" style={{ width: `${value / committed * 100}%` }} /></div></div>)}</div></section><section className="operational-panel p-5"><p className="section-eyebrow">Replacement depth</p><p className="tabular mt-4 text-4xl font-semibold">{Math.round(standby / required * 100)}%</p><p className="mt-2 text-xs text-muted-foreground">Authorized standby relative to required quantity.</p><p className="mt-6 flex gap-2 border-t border-white/[0.07] pt-4 text-xs text-muted-foreground"><CircleAlert className="h-3.5 w-3.5 text-accent" />Coordinates are unavailable; no map points are fabricated.</p></section></div>; }
function TraceabilityView() { const steps = ['Farmer','Production Lot','Allocation','Received Sublot','Shipment','Delivery','Buyer Confirmation','Trade Evidence']; return <section className="operational-panel p-5"><div className="flex items-center justify-between"><div><p className="section-eyebrow">Provenance graph</p><h2 className="mt-2 text-lg font-semibold">Available relationship chain</h2></div><DataTrustIndicator state="SYSTEM DERIVED" /></div><div className="mt-7 flex flex-col items-center">{steps.map((step,index) => <div key={step} className="flex flex-col items-center"><button className={`flex min-w-64 items-center gap-3 rounded-md border px-4 py-3 text-left text-sm ${index < 3 ? 'border-success/25 bg-success/[0.06]' : 'border-white/[0.07] text-muted-foreground'}`}><span className={`grid h-6 w-6 place-items-center rounded ${index < 3 ? 'bg-success/10 text-success' : 'bg-white/[0.04]'}`}>{index < 3 ? <Check className="h-3 w-3" /> : <Package className="h-3 w-3" />}</span>{step}</button>{index < steps.length - 1 && <ArrowDown className="my-1.5 h-4 w-4 text-muted-foreground/40" />}</div>)}</div><p className="mt-5 text-center text-xs text-muted-foreground">Only planning links are currently available. Physical and evidence nodes remain unresolved.</p></section>; }
function AnalyticsView({ required, committed, standby, shortfall, fulfilment, data }: { required:number; committed:number; standby:number; shortfall:number; fulfilment?:Context['fulfilment']; data:Context['data'] }) { return <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Summary label="Coverage rate" value={`${Math.round(committed/required*100)}%`} tone="success" /><Summary label="Open shortfall" value={`${shortfall} kg`} tone={shortfall?'critical':'success'} /><Summary label="Standby ratio" value={`${Math.round(standby/required*100)}%`} tone="info" /><Summary label="Accepted ratio" value={`${Math.round(Number(fulfilment?.accepted_kg ?? 0)/required*100)}%`} /><Summary label="Risk snapshot" value={data.risk?.label ?? 'UNKNOWN'} /><Summary label="Received" value={`${fulfilment?.received_kg ?? '—'} kg`} tone="info" /><Summary label="Rejected" value={`${fulfilment?.rejected_kg ?? '—'} kg`} tone="critical" /><Summary label="Recovery state" value={data.latest_recovery?.status?.toUpperCase() ?? 'NONE'} /></div>; }
function AgentView({ data, events }: { data: Context['data']; events: Context['events'] }) { return <section className="operational-panel overflow-hidden"><div className="grid gap-4 border-b border-white/[0.07] p-5 sm:grid-cols-4"><Mini label="Trigger" value={data.latest_disruption ? `${data.latest_disruption.lost_kg} kg lost` : 'No disruption'} /><Mini label="Observation" value={`${data.unfilled_quantity_kg} kg shortfall`} /><Mini label="Outcome" value={data.latest_recovery?.status === 'completed' ? 'Coverage restored' : data.supply_health} /><Mini label="Approval" value="Authorized policy" /></div><div className="p-5"><p className="section-eyebrow">Tools / services used</p><div className="mt-3 flex flex-wrap gap-2">{['Supply inventory','Eligibility engine','Standby registry','Economics engine'].map(item => <span key={item} className="rounded border border-white/[0.08] px-2.5 py-1.5 text-xs text-muted-foreground">{item}</span>)}</div><p className="mt-6 section-eyebrow">Audit links</p><div className="mt-3 divide-y divide-white/[0.07]">{events.map(event => <div key={event.id} className="flex justify-between py-3 text-xs"><span>{event.event_type.replace(/\./g,' ')}</span><span className="font-mono text-muted-foreground">{event.id}</span></div>)}</div></div></section>; }
function ActivityView({ events }: { events: Context['events'] }) { return <section className="operational-panel overflow-hidden"><div className="flex items-center gap-2 border-b border-white/[0.07] px-5 py-4 text-xs text-muted-foreground"><Search className="h-3.5 w-3.5" />Search and global filters require a global event API.</div><ol className="divide-y divide-white/[0.06]">{events.map(event => <li key={event.id} className="grid gap-3 px-5 py-4 sm:grid-cols-[150px_minmax(0,1fr)_120px]"><time className="tabular text-xs text-muted-foreground">{new Date(event.occurred_at).toLocaleString()}</time><div><p className="text-sm font-medium">{event.event_type.replace(/\./g,' ')}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{event.id}</p></div><span className="text-xs uppercase tracking-wider text-muted-foreground sm:text-right">{event.actor_type}</span></li>)}</ol></section>; }
function IntegrationView() { const configured = Boolean(process.env.NEXT_PUBLIC_SUPABASE_URL && process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY); return <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Integration name="Identity" detail="Supabase authentication" state={configured?'CONFIGURED':'NOT CONNECTED'} /><Integration name="Domain API" detail={process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'} state="CONFIGURED" /><Integration name="Procurement / ERP" detail="No connector configured" state="NOT CONNECTED" /><Integration name="Messaging" detail="No connector configured" state="NOT CONNECTED" /><Integration name="Logistics" detail="No connector configured" state="NOT CONNECTED" /><Integration name="Government systems" detail="No connector configured" state="NOT CONNECTED" /></div>; }
function SettingsView() { return <div className="grid gap-6 lg:grid-cols-2"><section className="operational-panel p-5"><p className="section-eyebrow">Environment</p><dl className="mt-4 divide-y divide-white/[0.07]"><Pair label="Application mode" value={process.env.NEXT_PUBLIC_APP_MODE === 'demo'?'DEMO':'LIVE'} /><Pair label="Authentication" value={process.env.NEXT_PUBLIC_AUTH_MODE === 'demo'?'DEMO BYPASS':'SUPABASE'} /><Pair label="API authority" value={process.env.NEXT_PUBLIC_API_URL ?? 'http://localhost:8000'} /></dl></section><section className="operational-panel"><HonestEmpty title="Role-based administration unavailable" detail="The current authorization model authenticates users but does not implement procurement, warehouse, coordinator, or administrator permissions." action="RBAC requires backend policy and persistence work." /></section></div>; }
function RegistryEmpty({ icon: Icon, title, detail }: { icon: typeof FileCheck2; title:string; detail:string }) { return <section className="operational-panel"><div className="p-5"><p className="section-eyebrow">Authoritative registry</p></div><HonestEmpty title={title} detail={detail} /><p className="flex items-center gap-2 px-5 py-4 text-xs text-muted-foreground"><Icon className="h-4 w-4" />Missing evidence remains visible as missing.</p></section>; }
function Integration({ name, detail, state }: { name:string; detail:string; state:'CONFIGURED'|'NOT CONNECTED' }) { return <div className="operational-panel p-5"><div className="flex items-start justify-between"><span className="grid h-9 w-9 place-items-center rounded-md bg-accent/10 text-accent"><PlugZap className="h-4 w-4" /></span><StatusBadge status={state==='CONFIGURED'?'VERIFIED':'NOT ASSESSED'} /></div><h2 className="mt-5 font-semibold">{name}</h2><p className="mt-1 text-xs text-muted-foreground">{detail}</p><p className="mt-4 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{state}</p></div>; }
function Summary({ label, value, tone }: { label:string; value:string; tone?:'success'|'critical'|'warning'|'info' }) { return <div className="operational-panel p-5"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={`tabular mt-2 text-2xl font-semibold ${tone==='success'?'text-success':tone==='critical'?'text-destructive':tone==='warning'?'text-warning':tone==='info'?'text-accent':''}`}>{value}</p><div className="mt-3"><DataTrustIndicator state="SYSTEM DERIVED" /></div></div>; }
function Mini({ label, value }: { label:string; value:string }) { return <div><p className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="tabular mt-1 text-xs font-medium">{value}</p></div>; }
function Pair({ label, value }: { label:string; value:string }) { return <div className="flex items-center justify-between gap-4 py-3 text-xs"><dt className="text-muted-foreground">{label}</dt><dd className="text-right font-medium">{value}</dd></div>; }
