'use client';

import { AlertTriangle, Beaker, FlaskConical, LockKeyhole } from 'lucide-react';
import { useState } from 'react';
import { AppShell } from '@/components/AppShell';
import { DataTrustIndicator } from '@/components/DataTrustIndicator';
import { StatusBadge } from '@/components/StatusBadge';
import { Breadcrumbs, WorkspaceHeader } from '@/components/WorkspacePrimitives';
import { useAssurance } from '@/hooks/useAssurance';

const requirementId = process.env.NEXT_PUBLIC_REQUIREMENT_ID ?? (process.env.NEXT_PUBLIC_APP_MODE === 'demo' ? '00000000-0000-0000-0000-000000000500' : '');

export function ScenarioLab() {
  const assurance = useAssurance(requirementId); const [loss, setLoss] = useState(80); const [scenario, setScenario] = useState<'FARMER DROPOUT'|'SUPPLY REDUCTION'|'QUALITY REJECTION'>('FARMER DROPOUT');
  if (!assurance.data) return <div className="grid min-h-screen place-items-center text-sm text-muted-foreground">{assurance.isLoading ? 'Loading simulation inputs…' : 'Scenario inputs unavailable.'}</div>;
  const data = assurance.data; const current = Number(data.committed_quantity_kg); const required = Number(data.requirement.required_quantity_kg); const standby = Number(data.standby_quantity_kg); const afterLoss = Math.max(0, current - loss); const shortfall = Math.max(0, required - afterLoss); const possible = Math.min(shortfall, standby); const afterRecovery = afterLoss + possible; const remaining = Math.max(0, required - afterRecovery); const candidates = data.allocations.filter(item => item.role === 'STANDBY' && ['STANDBY','ACTIVATED'].includes(item.status));
  return <AppShell programme={`${data.requirement.buyer_name} · ${data.requirement.crop}`}><main className="mx-auto max-w-6xl px-4 py-6 sm:px-6 lg:px-8 lg:py-8"><Breadcrumbs items={[{label:'Command Center',href:'/'},{label:'Scenario Lab'}]} /><WorkspaceHeader eyebrow="Simulation" title="KoroFarm Scenario Lab" description="Explore bounded supply disruptions without writing to live domain state." trust={<span className="inline-flex items-center gap-2 rounded-md border border-warning/30 bg-warning/10 px-3 py-2 text-xs font-semibold text-warning"><FlaskConical className="h-4 w-4" />SIMULATION</span>} />
    <div className="grid gap-6 lg:grid-cols-[320px_minmax(0,1fr)]"><aside className="operational-panel p-5"><p className="section-eyebrow">Scenario inputs</p><label className="mt-5 block text-xs font-medium" htmlFor="scenario">Disruption type</label><select id="scenario" value={scenario} onChange={event => setScenario(event.target.value as typeof scenario)} className="mt-2 h-10 w-full rounded-md border border-white/[0.1] bg-secondary px-3 text-sm"><option>FARMER DROPOUT</option><option>SUPPLY REDUCTION</option><option>QUALITY REJECTION</option></select><label className="mt-6 flex justify-between text-xs font-medium" htmlFor="loss"><span>Quantity impact</span><strong className="tabular text-warning">{loss} kg</strong></label><input id="loss" type="range" min="10" max={Math.min(200,current)} step="10" value={loss} onChange={event => setLoss(Number(event.target.value))} className="mt-3 w-full accent-[#43c982]" /><div className="mt-6 rounded-md border border-white/[0.07] bg-white/[0.025] p-3 text-xs text-muted-foreground"><p className="flex items-center gap-2 font-medium text-foreground"><LockKeyhole className="h-3.5 w-3.5 text-primary" />No live writes</p><p className="mt-2 leading-5">Results are computed in this browser and never enter the audit ledger.</p></div></aside>
      <div className="space-y-6"><section className="operational-panel overflow-hidden"><div className="grid sm:grid-cols-3"><Stage label="Before" committed={current} shortfall={Math.max(0,required-current)} status={data.supply_health} /><Stage label="After disruption" committed={afterLoss} shortfall={shortfall} status={shortfall?'AT RISK':'COVERED'} active /><Stage label="Proposed recovery" committed={afterRecovery} shortfall={remaining} status={remaining?'ESCALATION REQUIRED':'COVERED'} /></div></section><section className="operational-panel p-5"><div className="flex items-start justify-between gap-4"><div><p className="section-eyebrow">Authorized standby candidates</p><h2 className="mt-2 text-lg font-semibold">Recovery possibilities</h2></div><DataTrustIndicator state="SYSTEM DERIVED" detail="Simple quantity view over current authorized standby; not a persisted recovery decision" /></div><div className="mt-5 divide-y divide-white/[0.07]">{candidates.map((candidate,index) => <div key={candidate.id} className="grid gap-3 py-4 sm:grid-cols-[minmax(0,1fr)_100px_120px]"><div><p className="text-sm font-medium">{candidate.farmer_name}</p><p className="mt-1 text-xs text-muted-foreground">{candidate.parish} · {candidate.production_lot_id}</p></div><p className="tabular text-sm">{Math.min(Number(candidate.quantity_kg), Math.max(0, possible - candidates.slice(0,index).reduce((s,item)=>s+Number(item.quantity_kg),0)))} kg</p><span className="text-xs text-accent">Authorized standby</span></div>)}</div>{!candidates.length && <p className="mt-5 text-sm text-muted-foreground">No authorized standby is visible.</p>}</section><section className="grid gap-4 sm:grid-cols-3"><Fact label="Simulated loss" value={`−${loss} kg`} tone="warning" /><Fact label="Potential recovery" value={`+${possible} kg`} tone="success" /><Fact label="Economic impact" value="NOT CALCULATED" /></section><p className="flex gap-2 text-xs leading-5 text-muted-foreground"><AlertTriangle className="mt-0.5 h-3.5 w-3.5 shrink-0 text-warning" />This lab does not reproduce backend eligibility, risk, or economics engines. Use the live requirement workspace to execute and audit an authorized recovery.</p></div></div>
  </main></AppShell>;
}
function Stage({label,committed,shortfall,status,active}:{label:string;committed:number;shortfall:number;status:string;active?:boolean}) { return <div className={`border-b border-white/[0.07] p-5 last:border-0 sm:border-b-0 sm:border-r ${active?'bg-warning/[0.035]':''}`}><p className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</p><p className="tabular mt-3 text-3xl font-semibold">{committed}<span className="ml-1 text-sm text-muted-foreground">kg</span></p><p className={`tabular mt-2 text-xs ${shortfall?'text-destructive':'text-muted-foreground'}`}>{shortfall} kg shortfall</p><div className="mt-4"><StatusBadge status={status} /></div></div>; }
function Fact({label,value,tone}:{label:string;value:string;tone?:'warning'|'success'}) { return <div className="operational-panel p-4"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className={`tabular mt-2 text-lg font-semibold ${tone==='warning'?'text-warning':tone==='success'?'text-success':''}`}>{value}</p></div>; }
